import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.scss';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['cyrillic'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Header />
				<main className='container'>
					{children}
				</main>
				<Footer />

			</body>
		</html>
	)
}
